### ISSUE TITLE
Matching recent year throws TypeError

### ISSUE THREAD

**Issue by alasjo** [dwolfhub/zxcvbn-python#1]
Passing a string representation of a recent year with, for example `zxcvbn("2000")` throws the following error ('_sre.SRE_Match' object is not subscriptable):

    Traceback (most recent call last):
      File "C:/Users/Me/PycharmProjects/Test/pass.py", line 5, in <module>
        print(zxcvbn("2000"))
      File "C:\Python34\lib\site-packages\zxcvbn\__init__.py", line 13, in zxcvbn
        result = scoring.most_guessable_match_sequence(password, matches)
      File "C:\Python34\lib\site-packages\zxcvbn\scoring.py", line 199, in most_guessable_match_sequence
        update(m, 1)
      File "C:\Python34\lib\site-packages\zxcvbn\scoring.py", line 111, in update
        pi = estimate_guesses(m, password)
      File "C:\Python34\lib\site-packages\zxcvbn\scoring.py", line 241, in estimate_guesses
        guesses = estimation_functions[match['pattern']](match)
      File "C:\Python34\lib\site-packages\zxcvbn\scoring.py", line 310, in regex_guesses
        year_space = abs(int(match['regex_match'][0]) - REFERENCE_YEAR)
    TypeError: '_sre.SRE_Match' object is not subscriptable

**Comment by alasjo** [comment]
Found an easy solution for the line 310 in scoring.py which I have made a pull request for: #2

**Comment by dwolfhub** [comment]
Thanks for reporting and PR.
