### ISSUE TITLE
Number too large to convert from Integer to Float (online_throttling_100_per_hour)

### ISSUE THREAD

**Issue by m33x** [dwolfhub/zxcvbn-python#25]
I mean the error message says it all ;)

`Traceback (most recent call last):
  File "add_pw_descriptors.py", line 61, in <module>
    main()
  File "add_pw_descriptors.py", line 55, in main
    strength = str(heur.get_strength_user_pw(username, pw))
  File "../helpers/heuristics.py", line 201, in get_strength_user_pw
    results = zxcvbn(password, user_inputs=[username])
  File "/data/stuff/venv-pypy/site-packages/zxcvbn/__init__.py", line 32, in zxcvbn
    attack_times = time_estimates.estimate_attack_times(result['guesses'])
  File "/data/stuff/venv-pypy/site-packages/zxcvbn/time_estimates.py", line 3, in estimate_attack_times
    'online_throttling_100_per_hour': float(guesses) / (100.0 / 3600.0),
OverflowError: long int too large to convert to float`

**Comment by dwolfhub** [comment]
@m33x should be fixed in v4.4.20

thanks for reporting!
